update to account for tts output

diff --git a/charts/local-ai/templates/deployment.yaml b/charts/local-ai/templates/deployment.yaml
--- a/charts/local-ai/templates/deployment.yaml
+++ b/charts/local-ai/templates/deployment.yaml
@@ -81,36 +81,50 @@ spec:
               MODEL_DIR={{ .Values.deployment.modelsPath }}
               FORCE_DOWNLOAD={{ .Values.models.forceDownload }}
               URLS="{{ $urls }}"
+              LOCK_DIR=/tmp/model-download-locks
 
               mkdir -p "$MODEL_DIR"
+              mkdir -p "$LOCK_DIR"
+              mkdir -p "/tmp/generated/images"
+              mkdir -p "/tmp/generated/audio"
+
 
               echo "$URLS" | awk -F, '{for (i=1; i<=NF; i++) print $i}' | while read -r line; do
                   url=$(echo "$line" | awk '{print $1}')
                   auth=$(echo "$line" | awk '{print $2}')
+                  full_filename=$(basename "$url" .bin)
+                  short_filename=$(echo "$full_filename" | cut -c1-20)
+                  hash=$(echo "$full_filename" | sha256sum | cut -c1-12)
+                  filename="${short_filename}_${hash}"
+                  lockfile="$LOCK_DIR/$filename.lock"
 
-                  if [ -n "$url" ]; then
-                      filename=$(basename "$url" .bin)
+                  if [ -e "$MODEL_DIR/$filename" ]; then
+                      echo "File $filename already exists. Skipping download."
+                      continue
+                  fi
 
-                      if [ "$FORCE_DOWNLOAD" = false ] && [ -f "$MODEL_DIR/$filename" ]; then
-                          echo "File $filename already exists. Skipping download."
-                          continue
-                      fi
+                  if [ -e "$lockfile" ]; then
+                      echo "Another pod is downloading $filename. Waiting for download to complete."
+                      while [ -e "$lockfile" ]; do sleep 1; done
+                      continue
+                  fi
 
-                      rm -f "$MODEL_DIR/$filename"
+                  touch "$lockfile"
 
-                      echo "Downloading $filename"
+                  echo "Downloading $filename"
+                  if [ -n "$auth" ]; then
+                      wget --header "Authorization: Basic $auth" "$url" -O "$MODEL_DIR/$filename"
+                  else
+                      wget "$url" -O "$MODEL_DIR/$filename"
+                  fi
 
-                      if [ -n "$auth" ]; then
-                          wget --header "Authorization: Basic $auth" "$url" -O "$MODEL_DIR/$filename"
-                      else
-                          wget "$url" -O "$MODEL_DIR/$filename"
-                      fi
-
-                      if [ "$?" -ne 0 ]; then
-                          echo "Download failed."
-                      else
-                          echo "Download completed."
-                      fi
+                  if [ "$?" -ne 0 ]; then
+                      echo "Download failed."
+                      rm -f "$lockfile"
+                      exit 1
+                  else
+                      echo "Download completed."
+                      rm -f "$lockfile"
                   fi
               done
           volumeMounts:
